env:
  browser: true
  es2020: true
parser: 'babel-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
rules: { 'react/prop-types': 0 }
